exchanges:
  mexc:
    spot:
      socket_url: 
        public: "wss://wbs-api.mexc.com/ws"
        private: "wss://wbs-api.mexc.com/ws?listenKey=${listenKey}" 
      max_subscription: 30
      ping_interval: 30
      max_listenKey: 60
      each_listenKey_perMaxWebsocketConnection: 5
      ping_message: {"method": "PING"}
      available_kline_intervals: ['Min1', 'Min5','Min15', 'Min30', 'Min60', 'Hour4', 'Hour8', 'Day1', 'Week1', 'Month1']
      topic_template:
          public:
              trades: "spot@public.aggre.deals.v3.api.pb@(100ms|10ms)@${symbol}"
              order_book_limited_depths: "spot@public.limit.depth.v3.api.pb@{symbol}@{ob_depth_level}"
              kline: "spot@public.kline.v3.api.pb@${symbol}@${interval}"
              book_ticker: "spot@public.aggre.bookTicker.v3.api.pb@(100ms|10ms)@${symbol}"
          private:
              spot_account_upate: {"method": "SUBSCRIPTION", "params": "spot@private.account.v3.api.pb"}
              spot_account_deals: {"method": "SUBSCRIPTION", "params":"spot@private.deals.v3.api.pb"}
              spot_account_orders: {"method": "SUBSCRIPTION", "params":"spot@private.orders.v3.api.pb"}
    futures:
      socket_url: 
        public: "wss://contract.mexc.com/edge"
        private: 
      max_subscription: 30
      ping_interval: 30
      max_listenKey: 60
      each_listenKey_perMaxWebsocketConnection: 5
      ping_message: {"method": "ping"}
      topic_template:
          public:
              trades: "spot@public.aggre.deals.v3.api.pb@(100ms|10ms)@${symbol}"
              order_book_limited_depths: "spot@public.limit.depth.v3.api.pb@{symbol}@{ob_depth_level}"
              kline: "spot@public.kline.v3.api.pb@${symbol}@${interval}"
              book_ticker: "spot@public.aggre.bookTicker.v3.api.pb@(100ms|10ms)@${symbol}"
          private:
              spot_account_upate: {"method": "SUBSCRIPTION", "params": "spot@private.account.v3.api.pb"}
              spot_account_deals: {"method": "SUBSCRIPTION", "params":"spot@private.deals.v3.api.pb"}
              spot_account_orders: {"method": "SUBSCRIPTION", "params":"spot@private.orders.v3.api.pb"}